export function defaultOwnershipBoundary(): any;
export function ownershipBoundaryForMaintainedSurface(...args: any[]): any;
export function reviewBoundaryForCapability(...args: any[]): any;
export function reviewBoundaryForEntity(...args: any[]): any;
export function reviewBoundaryForJourneyDoc(...args: any[]): any;
export function reviewBoundaryForMaintainedClassification(...args: any[]): any;
export function reviewBoundaryForProjection(...args: any[]): any;
export function reviewBoundaryForWorkflowDoc(...args: any[]): any;
export function reviewBoundaryForAcceptanceCriterion(...args: any[]): any;
export function reviewBoundaryForBug(...args: any[]): any;
export function reviewBoundaryForDocument(...args: any[]): any;
export function reviewBoundaryForDomain(...args: any[]): any;
export function reviewBoundaryForPitch(...args: any[]): any;
export function reviewBoundaryForRequirement(...args: any[]): any;
export function reviewBoundaryForTask(...args: any[]): any;
